source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'

target "SMTH" do

pod 'UMengSocial'
pod 'UMengAnalytics'
pod 'GDTMobSDK'

end

target "SMTH Pro" do
    
    pod 'UMengSocial'
    pod 'UMengAnalytics'
    pod 'GDTMobSDK'
end
